POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "About Myself",
    "author": "Dorian Gray",
    "url": "http://www.blogs.com/dorian-gray/about_myself",
    "likes": 1,
    "userId": "5ff5cc3cfd3e1639ac628eff"
}
