POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphenoiLCJpZCI6IjVmZWIwNmZjMzNkOTdkMzEwMGQxMTc1MCIsImlhdCI6MTYxMTIzMzc5M30.iSR3ED-2DsDp5f2YcHSatF4hNfJyPGfIBhRKh5eIjKM

{
    "title": "Tokens 101",
    "author": "Tony Token",
    "url": "http://www.blogs.com/tony-token/tokens_101",
    "likes": 3
}
