POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Architecture",
    "author": "Kristen McIntyre",
    "url": "http://www.blogs.com/koodaus101",
    "likes": 16
}    