DELETE http://localhost:3003/api/blogs/6009c7cfcabd3c0de07f7867
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImphenoiLCJpZCI6IjVmZWIwNmZjMzNkOTdkMzEwMGQxMTc1MCIsImlhdCI6MTYxMTI1MzY3OH0.hn7Y12vBN6Spkd2IcNIQxiAC0geR35Mm5MzYf3Xq-7c
